### PR TITLE
Added maintainers.md file

### PR DESCRIPTION
**Pull request by helloshiv01**
added md file

### CODE REVIEW

**Review by joewxboy — APPROVED** [review]

**Comment by joewxboy** [comment]
Congratulations, Shiv.  You are now officially a project Contributor.

**Comment by helloshiv01** [comment]
But i have not recieved Pull/merge request approved message from
Hacktoberfest
:(

**Comment by joewxboy** [comment]
It took me a week to get my notification from them.

**Comment by helloshiv01** [comment]
i think i have not recieved the aprroval request yet due to DCO.i think only only author can signed off.

**Pull request merged**
